import type { Metadata } from "next";
import { Livvic } from "next/font/google";

import "./globals.css";

const livvic = Livvic({
  variable: "--font-livvic",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MyTeam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${livvic.variable} mx-auto max-w-7xl bg-[#014E56] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
