import type { Metadata } from "next";
import { Livvic } from "next/font/google";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ReadyToStart from "@/components/ReadyToStart";

import "./globals.css";

const livvic = Livvic({
  variable: "--font-livvic",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MyTeam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${livvic.className} mx-auto max-w-7xl bg-[#014E56] antialiased`}
      >
        <Header />
        <main className="mt-32">{children}</main>
        <ReadyToStart />
        <Footer />
      </body>
    </html>
  );
}
